site_name: City Data Model (CDM) - Transport
site_description: The ontology for the Transport portion of the City Data Model
repo_url: https://github.com/k-vaughn/ontology-cdm-p3
nav:
- Home: index.md
- Micromobility Network Pattern (transportnetwork):
  - Micromobility Lane: classes/transportnetwork__MicromobilityLane.md
  - Micromobility Link: classes/transportnetwork__MicromobilityLink.md
  - Micromobility Network: classes/transportnetwork__MicromobilityNetwork.md
  - Micromobility Path: classes/transportnetwork__MicromobilityPath.md
  - Micromobility Path Section: classes/transportnetwork__MicromobilityPathSection.md
  - Micromobility Path Segment: classes/transportnetwork__MicromobilityPathSegment.md
- Pedestrian Network Pattern (transportnetwork):
  - Footpath: classes/transportnetwork__Footpath.md
  - Footpath Lane: classes/transportnetwork__FootpathLane.md
  - Footpath Link: classes/transportnetwork__FootpathLink.md
  - Footpath Network: classes/transportnetwork__FootpathNetwork.md
  - Footpath Section: classes/transportnetwork__FootpathSection.md
  - Footpath Segment: classes/transportnetwork__FootpathSegment.md
- Public Transport System Pattern (transportnetwork):
  - Group Of Lines: classes/transportnetwork__GroupOfLines.md
  - Point On Route: classes/transportnetwork__PointOnRoute.md
  - Public Transport Element: classes/transportnetwork__PublicTransportElement.md
  - Public Transport Line: classes/transportnetwork__PublicTransportLine.md
  - Public Transport Route: classes/transportnetwork__PublicTransportRoute.md
  - Public Transport System: classes/transportnetwork__PublicTransportSystem.md
  - Route Point: classes/transportnetwork__RoutePoint.md
- Rail Network Pattern (transportnetwork):
  - Rail Corridor: classes/transportnetwork__RailCorridor.md
  - Rail Network: classes/transportnetwork__RailNetwork.md
  - Rail Section: classes/transportnetwork__RailSection.md
  - Track Link: classes/transportnetwork__TrackLink.md
  - Track Segment: classes/transportnetwork__TrackSegment.md
- Road Network Pattern (transportnetwork):
  - Road: classes/transportnetwork__Road.md
  - Road Lane: classes/transportnetwork__RoadLane.md
  - Road Link: classes/transportnetwork__RoadLink.md
  - Road Link User Type: classes/transportnetwork__RoadLinkUserType.md
  - Road Network: classes/transportnetwork__RoadNetwork.md
  - Road Section: classes/transportnetwork__RoadSection.md
  - Road Segment: classes/transportnetwork__RoadSegment.md
- Transport Alert Pattern (transportnetwork):
  - Alert: classes/transportnetwork__Alert.md
  - Transport Alert: classes/transportnetwork__TransportAlert.md
- Transport Network Pattern (transportnetwork):
  - Junction: classes/transportnetwork__Junction.md
  - Network Element: classes/transportnetwork__NetworkElement.md
  - Scheduled Code: classes/transportnetwork__ScheduledCode.md
  - Transport Network: classes/transportnetwork__TransportNetwork.md
  - Transport Node: classes/transportnetwork__TransportNode.md
  - Travelled Way: classes/transportnetwork__TravelledWay.md
  - Travelled Way Lane: classes/transportnetwork__TravelledWayLane.md
  - Travelled Way Link: classes/transportnetwork__TravelledWayLink.md
  - Travelled Way Section: classes/transportnetwork__TravelledWaySection.md
  - Travelled Way Segment: classes/transportnetwork__TravelledWaySegment.md
- Travel Corridor Pattern (transportnetwork):
  - Travel Corridor: classes/transportnetwork__TravelCorridor.md
  - Travel Corridor Link: classes/transportnetwork__TravelCorridorLink.md
  - Travel Corridor Segment: classes/transportnetwork__TravelCorridorSegment.md
- ITS Pattern (transportnetwork): classes/transportnetwork__ITSPattern.md
site_url: https://github.com/k-vaughn/ontology-cdm-p3
copyright: <p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/">
  <a href="https://creativecommons.org/licenses/by/4.0/?ref=chooser-v1" target="_blank"
  rel="license noopener noreferrer" style="display:inline-block;">CC BY 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;"
  src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img
  style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1"
  alt=""></a></p>
theme:
  name: material
  features:
  - content.code.copy
  - content.status
  - content.tooltips
  - icons
  - navigation.path
  - navigation.top
  icon:
    repo: fontawesome/brands/github
    admonition:
      question: fontawesome/solid/comments
  palette:
  - scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
extra_css:
- stylesheets/extra.css
extra_javascript:
- https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
- javascripts/tablesort.js
plugins:
- search
- git-revision-date-localized:
    type: date
    fallback_to_build_date: true
markdown_extensions:
- abbr
- admonition
- attr_list
- def_list
- md_in_html
- meta
- footnotes
- pymdownx.blocks.caption
- pymdownx.details
- pymdownx.emoji
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
    use_pygments: true
- pymdownx.inlinehilite
- pymdownx.snippets:
    base_path: docs
    check_paths: true
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
- pymdownx.tabbed:
    alternate_style: true
- toc:
    permalink: true
extra:
  search:
    highlight: true
  hide:
  - title
  version:
    provider: mike
    alias: true
    default: latest
